#!/bin/sh
# Run OCS program under gdb
# $Id$

gdb=gdb
rm=/bin/rm

if [ $# -lt 1 ]
then
  echo "usage: `basename $0` program argument ..."
  exit 2
fi

program=$1
shift

for arg
do
  arguments="$arguments \"$arg\""
done
gdbcmdfile=/tmp/debug_$$

# commands to be executed by gdb
echo run $arguments >$gdbcmdfile

# run gdb 
$gdb -fullname -se $program -x $gdbcmdfile -nx 
$rm -f $gdbcmdfile
