#!/bin/sh
# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/oasys,v 1.1.1.1 1998-06-16 15:59:51 wg Exp $

SHELL=/bin/sh
export SHELL

if [ -z "$OCS" ]
then
  OCS=`expr $0 : '\(..*\)/bin/..*$'`
  export OCS
fi

if [ -z "$OCSOM" ]
then
  OCSOM=$OCS/lib/om
  export OCSOM
fi

if [ -z "$OCSPROJECT" ]
then
  OCSPROJECT=$OCSOM/specs/empty
  export OCSPROJECT
fi

if [ -z "$DOSFOP" ]
then
  DOSFOP=$OCS/dosfop
  export DOSFOP
fi

. $OCSOM/specs/ShSpecs.basic

OCSDIR=$OCS
export OCSDIR
mkdir OCS 1>/dev/null 2>&1
exec oasysbin -zdiagFile -zetaEnrichment -zforceUsedForAc $*
