#!/bin/sh
# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/om/scripts/ocsadmin,v 1.1.1.1 1998-06-16 15:59:51 wg Exp $

SHELL=/bin/sh
export SHELL

if [ -z "$OCS" ] 
then
  OCS=`expr $0 : '\(..*\)/bin/..*$'`  
  export OCS
fi

if [ -z "$OCSOM" ] 
then
  OCSOM=$OCS/lib/om
  export OCSOM
fi

if [ -z "$OCSPROJECT" ]
then
  OCSPROJECT=$OCSOM/specs/empty
  export OCSPROJECT
fi

if [ -z "$DOSFOP" ]
then
  DOSFOP=$OCS/dosfop
  export DOSFOP
fi

. $OCSOM/specs/ShSpecs.basic


if [ -z "$OCSSRC" ]
then
  OCSSRC=${OCS}/src
  export OCSSRC
fi

if [ "$1" = "-ocssrc" ]
then
  shift
  OCSSRC="$1"
  shift
fi

case "$1" in
  installlib)
    shift 
    while [ -n "$1" ]
    do
      $ECHO "Installing library $1 ..."
      . $OCSOM/specs/ShSpecs.lib.$1
      $OCSOM/etc/genshlib -v $LIBVERSION -d "${LIBDEPS}" ${LIBSYSTEMS} ${LIBDIR}
      eval ${LIBHOOK}
      shift
    done
    ;;
  *)
    $ECHO "usage: ocsadmin [ -ocssrc <path> ] ( installlib <libname> ... | ... )"
    exit 1
esac
  
exit 0
