#!/bin/sh

if [ -z "$OCS" ]
then
  OCS=`expr $0 : '\(..*\)/bin/..*$'`
  export OCS
fi

if [ -z "$OCSOM" ]
then
  OCSOM=$OCS/lib/om
  export OCSOM
fi

if [ -z "$OCSPROJECT" ]
then
  OCSPROJECT=$OCSOM/specs/empty
  export OCSPROJECT
fi

if [ -z "$OCSSHAPE" ]
then
  OCSSHAPE=$OCSOM/shape
  export OCSSHAPE
fi

if [ -z "$DOSFOP" ]
then
  DOSFOP=$OCS/dosfop
  export DOSFOP
fi

. $OCSOM/specs/ShSpecs.os.auto

${XSHAPE} -f $OCSSHAPE/Shapefile.release "$@"
