#!/bin/sh
# $Id$

SHELL=/bin/sh
export SHELL

if [ -z "$OCS" ]
then
  OCS=`expr $0 : '\(..*\)/bin/..*$'`
  export OCS
fi

if [ -z "$OCSOM" ]
then
  OCSOM=$OCS/lib/om
  export OCSOM
fi

if [ -z "$OCSPROJECT" ]
then
  OCSPROJECT=$OCSOM/specs/empty
  export OCSPROJECT
fi

if [ -z "$DOSFOP" ]
then
  DOSFOP=$OCS/dosfop
  export DOSFOP
fi

. $OCSOM/specs/ShSpecs.basic

exec $WISH $DOSFOP/tcl/pureDosfop.tcl $*
