#!/bin/sh
# script for bootstrapping JavaBind on installation time
# $Id$

# Root of OPAL_JAVA tree in distribution
opal_java=${OCSSRC}/lib/Tools/Java

# the Java interpreter
java=${JAVA:-java}

# install the javabind compiler classes
$ECHO "### installing the javabind compiler"
$MKDIR $OCSHOME/lib/classes 2>/dev/null || true
$CP -rf $opal_java/javabind/classes/* $OCSHOME/lib/classes
$CP -f $opal_java/javabind/javabind $OCSHOME/bin
$CHMOD +x $OCSHOME/bin/javabind

# bootstrap generated bindings
$ECHO "### generating basic bindings"
( cd $opal_java
pizzaclasses=`dirname $PIZZAPC`
pizzaclasses="$pizzaclasses/../classes"

echo "new classpath: ${OCS}/lib/classes:$pizzaclasses:$CLASSPATH"
  CLASSPATH=${OCSHOME}/lib/classes:$pizzaclasses:$CLASSPATH \
    $java opal.javabind.Driver -nolibs JavaBase.jb
)
