#!/bin/sh

LIBSRC=$NEWOCS/src/oc

. $OCSOM/specs/ShSpecs.basic
GENSHLIB=$OCSOM/etc/genshlib



###################
echo "Generating ${OC_SHARED}"
SYSTEMS="
        $LIBSRC/shared/extlib \
        $LIBSRC/shared/interOpal \
        $LIBSRC/shared/admin \
        $LIBSRC/shared/base \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_BASE} -lopal_base" $SYSTEMS ${OC_SHARED}

###################
echo "Generating ${OC_OC1}"
SYSTEMS="
	$LIBSRC/oc1/implAna \
	$LIBSRC/oc1/pattAna \
	$LIBSRC/oc1/acTrans \
	$LIBSRC/oc1/sigAna \
	$LIBSRC/oc1/parser \
	$LIBSRC/oc1/genInter \
	$LIBSRC/oc1/globSig \
	$LIBSRC/oc1/anaLib \
	$LIBSRC/oc1/absy \
	$LIBSRC/oc1/reps \
"
$GENSHLIB -v 2.3.0 -d "-L${OC_SHARED} -loc_shared -L${OPAL_BASE} -lopal_base" $SYSTEMS ${OC_OC1}

###################
echo "Generating ${OC_OC2}"
SYSTEMS="
	$LIBSRC/oc2/gen \
	$LIBSRC/oc2/trans \
	$LIBSRC/oc2/optim 
"
$GENSHLIB -v 2.3.0 -d "-L${OC_SHARED} -loc_shared -L${OPAL_BASE} -lopal_base" $SYSTEMS ${OC_OC2}
