#!/bin/sh
#
# Generate OPAL shared libraries
# 
# expects OCSOM to be set
#
# $Id$


LIBSRC=$NEWOCS/src/lib

. $OCSOM/specs/ShSpecs.basic

GENSHLIB=$OCSOM/etc/genshlib

###################
echo "Generating ${OPAL_BASE}"
SYSTEMS="
        $LIBSRC/Tools/Formatting \
        $LIBSRC/System/Unix \
        $LIBSRC/System/Commands \
        $LIBSRC/System/Debugging \
        $LIBSRC/System/Streams \
        $LIBSRC/AggregateTypes/Algorithms \
        $LIBSRC/AggregateTypes/MapLike \
        $LIBSRC/AggregateTypes/SetLike \
        $LIBSRC/AggregateTypes/TreeLike \
        $LIBSRC/AggregateTypes/SeqLike \
        $LIBSRC/AggregateTypes/UnionLike \
        $LIBSRC/AggregateTypes/ProductLike \
        $LIBSRC/Functions/Special \
        $LIBSRC/Functions/Orderings \
        $LIBSRC/Functions/General \
        $LIBSRC/BasicTypes \
        $LIBSRC/Internal/Strange \
        $LIBSRC/Internal/Compiler
"

$GENSHLIB -v 2.3.0 $SYSTEMS ${OPAL_BASE}

# ad-hoc stuff for basic library
cp -f $LIBSRC/Internal/Compiler/OCS/*.inter ${OPAL_BASE}
cp -f $LIBSRC/Internal/Compiler/OCS/*.h ${OPAL_BASE}
cp -f $LIBSRC/Internal/Compiler/OCS/*.opt ${OPAL_BASE}
cp -f $LIBSRC/System/Commands/_ostart.c ${OPAL_BASE}
cp -f $LIBSRC/System/Commands/_oasystart.c ${OPAL_BASE}


###################
echo "Generating ${OPAL_TCL}"
SYSTEMS="
        $LIBSRC/Tools/Tcl \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_BASE} -lopal_base $LIBTCL" $SYSTEMS ${OPAL_TCL}

###################
echo "Generating ${OPAL_TK}"
SYSTEMS="
        $LIBSRC/Tools/Tk \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_TCL} -lopal_tcl -L${OPAL_BASE} -lopal_base $LIBTK" $SYSTEMS ${OPAL_TK}

###################
echo "Generating ${OPAL_PARSERLIGHT}"
SYSTEMS="
        $LIBSRC/Tools/ParserLight \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_BASE} -lopal_base" $SYSTEMS ${OPAL_PARSERLIGHT}

###################
echo "Generating ${OPAL_WIN}"
SYSTEMS="
        $LIBSRC/Tools/OpalWin \
        $LIBSRC/Tools/OpalWinAdditions \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_TK} -lopal_tk -L${OPAL_TCL} -lopal_tcl -L${OPAL_PARSERLIGHT} -lopal_parserlight -L${OPAL_BASE} -lopal_base" $SYSTEMS ${OPAL_WIN}



###################
echo "Generating ${OPAL_READLINE}"
SYSTEMS="
        $LIBSRC/Tools/Readline \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_BASE} -lopal_base $LIBREADLINE" $SYSTEMS ${OPAL_READLINE}

###################
echo "Generating ${OPAL_JAVA}"
SYSTEMS="
        $LIBSRC/Tools/Java/JavaCheck \
        $LIBSRC/Tools/Java/JavaBase \
        $LIBSRC/Tools/Java/JavaVM \
"
$GENSHLIB -v 2.3.0 -d "-L${OPAL_BASE} -lopal_base $LIBJAVA" $SYSTEMS ${OPAL_JAVA}

###################
#echo "Generating ${OPAL_BFD}"
#SYSTEMS="
#        $LIBSRC/Tools/BFD \
#"
#$GENSHLIB -v 2.3.0 -d "-L${OPAL_BASE} -lopal_base $LIBBFD" $SYSTEMS ${OPAL_BFD}

