#!/bin/sh

echo "# automatically derived from Specs.X "

expand | \
${SED} \
    -e 's@#.*@@' \
    -e 's@^#.*@@' \
    -e 's@\([^ ][^ ]*\)[ ]*=[ ]*\(.*\)[ ]*$@\1=\"\3\"; export \1@' \
    -e 's@\([^ ][^ ]*\)[ ]*:=[ ]*\(.*\)[ ]*$@\1=\"\3\"; export \1@'
