#!/bin/sh

# Solaris sed doesn't works??

GNUSED=${SED}

echo "# automatically derived from Specs.X "
expand | \
${GNUSED} -e 's@#.*@@' \
    -e 's@^#.*@@' -e 's@\([^ ][^ ]*\)[ ]*\(=\|:=\)[ ]*\(.*\)[ ]*$@\1=\"\3\"; export \1@' 
