#!/usr/bin/perl

## find out locale
if (defined($ENV{"LC_ALL"})) {$loc = $ENV{"LC_ALL"};}
elsif (defined($ENV{"LC_TIME"})) {$loc = $ENV{"LC_TIME"}; }
elsif (defined($ENV{"LANG"})) {$loc = $ENV{"LANG"}; }
else {$loc = "C"; }

($lang, $country) = ($loc =~ /(.*)_(.*)\..*/);

# print "Language is $lang; Country is $country\n";

if ($lang eq "de") {
  $res = "german";
  }
else {
  $res = "english";  
}

$res =~ s/[ *.]/\\$&/g;
print $res;
