#!/usr/bin/perl

($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime;

## find out locale
if (defined($ENV{"LC_ALL"})) {$loc = $ENV{"LC_ALL"};}
elsif (defined($ENV{"LC_TIME"})) {$loc = $ENV{"LC_TIME"}; }
elsif (defined($ENV{"LANG"})) {$loc = $ENV{"LANG"}; }
else {$loc = "C"; }

($lang, $country) = ($loc =~ /(.*)_(.*)\..*/);
$year += 1900;

# print "Language is $lang; Country is $country\n";

if ($lang eq "de") {
  $Mon = (Januar, Februar, "März", April, Mai, Juni, Juli, August, September, Oktober, November, Dezember)[$mon];
  $res = "$mday. $Mon $year"; }
else {
  $Mon = (January, February, March, April, May, June, July, August, September, October, November, December)[$mon];
  $res = "$Mon $mday, $year";
}

$res =~ s/[ *.]/\\$&/g;
print $res;
