#!/bin/sh
#
## Copyright (C) 1993 by the author(s).
# 
# This software is published in the hope that it will be useful, but
# WITHOUT ANY WARRANTY for any part of this software to work correctly
# or as described in the manuals. See the ShapeTools Public License
# for details.
#
# Permission is granted to use, copy, modify, or distribute any part of
# this software but only under the conditions described in the ShapeTools 
# Public License. A copy of this license is supposed to have been given
# to you along with ShapeTools in a file named LICENSE. Among other
# things, this copyright notice and the Public License must be
# preserved on all copies.

#
# Author: Andreas Lampen (Andreas.Lampen@cs.tu-berlin.de)
#
# $Id$
#
if [ -f /bin/domainname ];
then 
domain=`/bin/domainname | sed -e 's/^\.//' | sed -e 's/^+//'`
else
domain=`hostname`
fi
echo $USER@$domain
