#!/bin/bash

VERSION=2.3h
OCSHDIR=ocs-$VERSION
OCSHOME=/home/florenz/opal/opt/ocsroot2/$OCSHDIR
OCSSRC=/home/florenz/opal/compiled/trunk/src

export OCSPROJECT=/home/florenz/opal/compiled/trunk/ProjectDefs

$OCSHOME/bin/ocsadmin -ocshome $OCSHOME -ocssrc $OCSSRC -ocsspecs $OCSSRC/om/specs $@
