#!/bin/sh

## this script expects a signature in file OCS/.signature, 
## a (normalized) proof head in OCS/.proof. Output is collected in OCS/.gpg,
## return value is 0, iff verification succeeds

# set language for simpler parsing
LANG=C gpg --verify OCS/.signature OCS/.proof &> OCS/.gpg