#!/bin/sh
# $__Header$

if [ -z "$OCS" ]
then
  OCS=`expr $0 : '\(..*\)/bin/..*$'`
  export OCS
fi

if [ -z "$OCSOM" ]
then
  OCSOM=$OCS/lib/om
  export OCSOM
fi


. $OCSOM/specs/ShSpecs.basic

pizzaclasses=`dirname $PIZZAPC`
pizzaclasses="$pizzaclasses/../classes"

echo "new classpath: ${OCS}/lib/classes:$pizzaclasses:$CLASSPATH"

CLASSPATH=${OCS}/lib/classes:$pizzaclasses:$CLASSPATH java opal.javabind.Driver -lib ${OPAL_JAVA} $*
