#!/usr/bin/perl

# This script changes absolute path names as still required by dosfop
# define the variables below and start the script

$oldManualRoot = "/home/uebb/kd/ocs/doc/bibopalicaman";
$newManualRoot = "/home/kd/ocs/doc/bibopalicaman";

@configFilesMan = ("config", "Toplevel.config");

$oldLibRoot = "/home/uebb/kd/ocs/src/lib";
$newLibRoot = "/home/kd/ocs/src/lib";

@configFilesLib = <*config>;

foreach $f (@configFilesMan) {
  open (INFILE, $f) or die "could not open $f";
  open (OUTFILE, ">$f.bak") or die "could not open $f.bak";
  while (<INFILE>) {
    s /$oldManualRoot/$newManualRoot/g;
    print OUTFILE
  }
  close INFILE;
  close OUTFILE;
  unlink $f;
  rename "$f.bak", "$f";
}

foreach $f (@configFilesLib) {
  open (INFILE, $f) or die "could not open $f";
  open (OUTFILE, ">$f.bak") or die "could not open $f.bak";
  while (<INFILE>) {
    s /$oldLibRoot/$newLibRoot/g;
    print OUTFILE
  }
  close INFILE;
  close OUTFILE;
  unlink $f;
  rename "$f.bak", "$f";
}
