#!/bin/sh
# $Id$

# throw away OCS_DL_PATH 
shift

# get arguments

#echo $*

sysname="$1"; shift
syspath="$1"; shift
objs="$*"

if [ "$sysname" = "." ]
then
  sysname=opalarchive
fi

(cd $syspath
${RM} -f lib${sysname}.a 2>/dev/null || true
${ARQ} lib${sysname}.a $objs
)
