#!/bin/sh
# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/oasys/scripts/archiver,v 1.2 1999-06-03 12:50:25 kd Exp $

# throw away OCS_DL_PATH 
shift

# get arguments

#echo $*

sysname="$1"; shift
syspath="$1"; shift
objs="$*"

if [ "$sysname" = "." ]
then
  sysname=opalarchive
fi

(cd $syspath
${RM} -f lib${sysname}.a 2>/dev/null || true
${ARQ} lib${sysname}.a $objs
)
