#!/bin/sh
# $Id$

# throw away OCS_DL_PATH 
shift

# get arguments
sfile=$1; shift
ofile=$1; shift
ipath=""
for p in $*
do
  ipath="$ipath -I$p"
done
# problems with -fpic in BFD??
#echo ${CC} ${MEDIUM_CC} ${DEBUG_CC} -c $sfile -o $ofile $ipath
exec ${CC} ${MEDIUM_CC} -c $sfile -o $ofile $ipath
