#!/bin/sh
# $Id$

# throw away OCS_DL_PATH 
shift

# get argument
ofile=$1; shift

#sofile=`echo $ofile | ${SED} s/o\$/so/`;
#nmufile=`echo $ofile | ${SED} s/o\$/nmu/`;
sofile=$1; shift
nmufile=$1; shift

# echo "creating $sofile ..."
${DLD} -o $sofile $ofile 
# echo "creating $nmufile ..."
exec ${NMU} $sofile > $nmufile
