#!/bin/sh
# $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/oasys/scripts/xccompiler,v 1.2 1999-06-03 12:50:26 kd Exp $

# throw away OCS_DL_PATH 
shift

# get argument
ofile=$1; shift

#sofile=`echo $ofile | ${SED} s/o\$/so/`;
#nmufile=`echo $ofile | ${SED} s/o\$/nmu/`;
sofile=$1; shift
nmufile=$1; shift

# echo "creating $sofile ..."
${DLD} -o $sofile $ofile 
# echo "creating $nmufile ..."
exec ${NMU} $sofile > $nmufile
