#!/bin/bash

opal_base=$HOME/sw/opt/ocs-2.4/lib/opal_base

./opalc -s S -I $opal_base BOOL DENOTATION Com Void
./opalc -i S -I $opal_base BOOL DENOTATION Com Void BasicIO Nat
./opalc -t S -I $opal_base BOOL DENOTATION Com Void BasicIO Nat
./opalc -m S -I $opal_base
#./opalc -c S -I $opal_base BOOL DENOTATION Com Void
