/* generated by javabind version 1.1a */
#include "JavaVM.oc.h"

jclass javabind_class_java_io_Serializable;


static void init_const_Ajava_Aio_ASerializable_ASORT(){
 javabind_class_java_io_Serializable =
    javabind_FindClass("java/io/Serializable");}
