/* generated by javabind version 1.1a */
#include "JavaVM.h"

jclass javabind_class_java_lang_reflect_Member;


static void init_const_Ajava_Alang_Areflect_AMember_ASORT(){
 javabind_class_java_lang_reflect_Member =
    javabind_FindClass("java/lang/reflect/Member");}
