/* generated by javabind version 1.1a */
#include "JavaVM.oc.h"

jclass javabind_class_java_lang_Object;


static void init_const_Ajava_Alang_AObject_ASORT(){
 javabind_class_java_lang_Object = javabind_FindClass("java/lang/Object");}
