/* generated by javabind version 1.1a */
#include "JavaVM.h"

jclass javabind_class_java_lang_reflect_Constructor;

extern OBJ _Ajava_Alang_Areflect_AConstructor_ASORT_AI1(OBJ x1){
 OBJ y;
 javabind_downcast(x1,javabind_class_java_lang_reflect_Constructor,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Alang_Areflect_AConstructor_ASORT_AI2(OBJ x1){
 OBJ y;
 javabind_downtest(x1,javabind_class_java_lang_reflect_Constructor,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Alang_Areflect_AConstructor_ASORT_AI3(OBJ x1){
 OBJ y;
 javabind_downcast(x1,javabind_class_java_lang_reflect_Constructor,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Alang_Areflect_AConstructor_ASORT_AI4(OBJ x1){
 OBJ y;
 javabind_downtest(x1,javabind_class_java_lang_reflect_Constructor,y);
 javabind_immutable_return(y);}


static void init_const_Ajava_Alang_Areflect_AConstructor_ASORT(){
 javabind_class_java_lang_reflect_Constructor =
    javabind_FindClass("java/lang/reflect/Constructor");}
