/* generated by javabind version 1.1a */
#include "JavaVM.h"

jclass javabind_class_java_io_OutputStream;

extern OBJ _Ajava_Aio_AOutputStream_ASORT_AI1(OBJ x1){
 OBJ y;
 javabind_downcast(x1,javabind_class_java_io_OutputStream,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Aio_AOutputStream_ASORT_AI2(OBJ x1){
 OBJ y;
 javabind_downtest(x1,javabind_class_java_io_OutputStream,y);
 javabind_immutable_return(y);}


static void init_const_Ajava_Aio_AOutputStream_ASORT(){
 javabind_class_java_io_OutputStream =
    javabind_FindClass("java/io/OutputStream");}
