/* generated by javabind version 1.1a */
#include "JavaVM.oc.h"

jclass javabind_class_java_io_InputStream;

extern OBJ _Ajava_Aio_AInputStream_ASORT_AI1(OBJ x1){
 OBJ y;
 javabind_downcast(x1,javabind_class_java_io_InputStream,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Aio_AInputStream_ASORT_AI2(OBJ x1){
 OBJ y;
 javabind_downtest(x1,javabind_class_java_io_InputStream,y);
 javabind_immutable_return(y);}


static void init_const_Ajava_Aio_AInputStream_ASORT(){
 javabind_class_java_io_InputStream =
    javabind_FindClass("java/io/InputStream");}
