/* generated by javabind version 1.1a */
#include "JavaVM.h"

extern jclass javabind_class_java_lang_Class;
extern jclass javabind_class_java_lang_reflect_Method;
extern jclass javabind_class_java_lang_ClassLoader;
extern jclass javabind_class_java_net_URL;
extern jclass javabind_class_java_lang_reflect_Field;
extern jclass javabind_class_java_lang_reflect_Constructor;
extern jclass javabind_class_java_lang_Object;
extern jclass javabind_class_java_io_Serializable;
extern jclass javabind_class_java_io_InputStream;
static jmethodID mId_AI1;
static jmethodID mId_AI2;
static jmethodID mId_AI3;
static jmethodID mId_AI4;
static jmethodID mId_AI5;
static jmethodID mId_AI6;
static jmethodID mId_AI7;
static jmethodID mId_AI8;
static jmethodID mId_AI9;
static jmethodID mId_AI10;
static jmethodID mId_AI11;
static jmethodID mId_AI12;
static jmethodID mId_AI13;
static jmethodID mId_AI14;
static jmethodID mId_AI15;
static jmethodID mId_AI16;
static jmethodID mId_AI17;
static jmethodID mId_AI18;
static jmethodID mId_AI19;
static jmethodID mId_AI20;
static jmethodID mId_AI21;
static jmethodID mId_AI22;
static jmethodID mId_AI23;
static jmethodID mId_AI24;
static jmethodID mId_AI25;
static jmethodID mId_AI26;
static jmethodID mId_AI27;
static jmethodID mId_AI28;
static jmethodID mId_AI29;
static jmethodID mId_AI30;
static jmethodID mId_AI31;
static jmethodID mId_AI32;
static jmethodID mId_AI33;
static jmethodID mId_AI34;
static jmethodID mId_AI35;
static jmethodID mId_AI36;
static jmethodID mId_AI37;
static jmethodID mId_AI38;
static jmethodID mId_AI39;
static jmethodID mId_AI40;

extern OBJ _Ajava_Alang_AClass_AI1(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asString(x1,_argv[0].l);
  _res =
     javabind_CallStaticObjectMethodA(javabind_class_java_lang_Class,mId_AI1,_argv)
    ;
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_temp(_argv[0].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI2(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI2,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI3(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jint _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallIntMethodA(_argv[0].l,mId_AI3,&_argv[1]);
  javabind_catch_fail();
  javabind_fromInt(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI4(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jboolean _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asObject(x2,_argv[1].l);
  _res = javabind_CallBooleanMethodA(_argv[0].l,mId_AI4,&_argv[1]);
  javabind_catch_fail();
  javabind_fromBoolean(_res,y);
  javabind_free_arg(x1);
  javabind_free_arg(x2);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI5(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI5,&_argv[1]);
  javabind_catch_fail();
  javabind_fromString(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI6(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  javabind_asObject(x1,_argv[0].l);
  javabind_CallVoidMethodA(_argv[0].l,mId_AI6,&_argv[1]);
  javabind_catch_fail();
  javabind_fromVoid(y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI7(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  javabind_asObject(x1,_argv[0].l);
  javabind_CallVoidMethodA(_argv[0].l,mId_AI7,&_argv[1]);
  javabind_catch_fail();
  javabind_fromVoid(y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI8(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  javabind_asObject(x1,_argv[0].l);
  javabind_asLong(x2,_argv[1].j);
  javabind_CallVoidMethodA(_argv[0].l,mId_AI8,&_argv[1]);
  javabind_catch_fail();
  javabind_fromVoid(y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI9(OBJ x1,OBJ x2,OBJ x3,OBJ unit){
 OBJ y;
 { jvalue _argv[4];
  javabind_asObject(x1,_argv[0].l);
  javabind_asLong(x2,_argv[1].j);
  javabind_asInt(x3,_argv[2].i);
  javabind_CallVoidMethodA(_argv[0].l,mId_AI9,&_argv[1]);
  javabind_catch_fail();
  javabind_fromVoid(y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI10(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  javabind_asObject(x1,_argv[0].l);
  javabind_CallVoidMethodA(_argv[0].l,mId_AI10,&_argv[1]);
  javabind_catch_fail();
  javabind_fromVoid(y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI11(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI11,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI12(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jboolean _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asObject(x2,_argv[1].l);
  _res = javabind_CallBooleanMethodA(_argv[0].l,mId_AI12,&_argv[1]);
  javabind_catch_fail();
  javabind_fromBoolean(_res,y);
  javabind_free_arg(x1);
  javabind_free_arg(x2);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI13(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jboolean _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asObject(x2,_argv[1].l);
  _res = javabind_CallBooleanMethodA(_argv[0].l,mId_AI13,&_argv[1]);
  javabind_catch_fail();
  javabind_fromBoolean(_res,y);
  javabind_free_arg(x1);
  javabind_free_arg(x2);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI14(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jboolean _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallBooleanMethodA(_argv[0].l,mId_AI14,&_argv[1]);
  javabind_catch_fail();
  javabind_fromBoolean(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI15(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jboolean _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallBooleanMethodA(_argv[0].l,mId_AI15,&_argv[1]);
  javabind_catch_fail();
  javabind_fromBoolean(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI16(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jboolean _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallBooleanMethodA(_argv[0].l,mId_AI16,&_argv[1]);
  javabind_catch_fail();
  javabind_fromBoolean(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI17(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI17,&_argv[1]);
  javabind_catch_fail();
  javabind_fromString(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI18(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI18,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI19(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI19,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI20(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI20,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_Class,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI21(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI21,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI22(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jint _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallIntMethodA(_argv[0].l,mId_AI22,&_argv[1]);
  javabind_catch_fail();
  javabind_fromInt(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI23(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI23,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_Object,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI24(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI24,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI25(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI25,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_Class,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI26(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI26,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_reflect_Field,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI27(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI27,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_reflect_Method,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI28(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI28,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_reflect_Constructor,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI29(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asString(x2,_argv[1].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI29,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI30(OBJ x1,OBJ x2,OBJ x3,OBJ unit){
 OBJ y;
 { jvalue _argv[4];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asString(x2,_argv[1].l);
  
    javabind_asObjectArray(1,javabind_class_java_lang_Class,_javabind_asObject,x3,_argv[2].l)
    ;
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI30,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);
  javabind_free_temp(_argv[2].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI31(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  
    javabind_asObjectArray(1,javabind_class_java_lang_Class,_javabind_asObject,x2,_argv[1].l)
    ;
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI31,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI32(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI32,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_Class,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI33(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI33,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_reflect_Field,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI34(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI34,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_reflect_Method,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI35(OBJ x1,OBJ unit){
 OBJ y;
 { jvalue _argv[2];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI35,&_argv[1]);
  javabind_catch_fail();
  
    javabind_fromObjectArray(1,javabind_class_java_lang_reflect_Constructor,_javabind_fromObject,_res,y)
    ;
  javabind_free_arg(x1);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI36(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asString(x2,_argv[1].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI36,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI37(OBJ x1,OBJ x2,OBJ x3,OBJ unit){
 OBJ y;
 { jvalue _argv[4];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asString(x2,_argv[1].l);
  
    javabind_asObjectArray(1,javabind_class_java_lang_Class,_javabind_asObject,x3,_argv[2].l)
    ;
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI37,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);
  javabind_free_temp(_argv[2].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI38(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  
    javabind_asObjectArray(1,javabind_class_java_lang_Class,_javabind_asObject,x2,_argv[1].l)
    ;
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI38,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI39(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asString(x2,_argv[1].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI39,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);}
 
 javabind_return(y);}

extern OBJ _Ajava_Alang_AClass_AI40(OBJ x1,OBJ x2,OBJ unit){
 OBJ y;
 { jvalue _argv[3];
  jobject _res;
  javabind_asObject(x1,_argv[0].l);
  javabind_asString(x2,_argv[1].l);
  _res = javabind_CallObjectMethodA(_argv[0].l,mId_AI40,&_argv[1]);
  javabind_catch_fail();
  javabind_fromObject(_res,y);
  javabind_free_arg(x1);
  javabind_free_temp(_argv[1].l);}
 
 javabind_return(y);}


static void init_const_Ajava_Alang_AClass(){
 mId_AI1 =
    javabind_GetStaticMethodID(javabind_class_java_lang_Class,"forName","(Ljava/lang/String;)Ljava/lang/Class;")
   ;
 mId_AI2 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getClass","()Ljava/lang/Class;")
   ;
 mId_AI3 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"hashCode","()I");
 mId_AI4 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"equals","(Ljava/lang/Object;)Z")
   ;
 mId_AI5 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"toString","()Ljava/lang/String;")
   ;
 mId_AI6 = javabind_GetMethodID(javabind_class_java_lang_Class,"notify","()V")
   ;
 mId_AI7 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"notifyAll","()V");
 mId_AI8 = javabind_GetMethodID(javabind_class_java_lang_Class,"wait","(J)V");
 mId_AI9 = javabind_GetMethodID(javabind_class_java_lang_Class,"wait","(JI)V")
   ;
 mId_AI10 = javabind_GetMethodID(javabind_class_java_lang_Class,"wait","()V");
 mId_AI11 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"newInstance","()Ljava/lang/Object;")
   ;
 mId_AI12 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"isInstance","(Ljava/lang/Object;)Z")
   ;
 mId_AI13 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"isAssignableFrom","(Ljava/lang/Class;)Z")
   ;
 mId_AI14 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"isInterface","()Z");
 mId_AI15 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"isArray","()Z");
 mId_AI16 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"isPrimitive","()Z");
 mId_AI17 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getName","()Ljava/lang/String;")
   ;
 mId_AI18 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getClassLoader","()Ljava/lang/ClassLoader;")
   ;
 mId_AI19 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getSuperclass","()Ljava/lang/Class;")
   ;
 mId_AI20 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getInterfaces","()[Ljava/lang/Class;")
   ;
 mId_AI21 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getComponentType","()Ljava/lang/Class;")
   ;
 mId_AI22 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getModifiers","()I");
 mId_AI23 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getSigners","()[Ljava/lang/Object;")
   ;
 mId_AI24 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaringClass","()Ljava/lang/Class;")
   ;
 mId_AI25 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getClasses","()[Ljava/lang/Class;")
   ;
 mId_AI26 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getFields","()[Ljava/lang/reflect/Field;")
   ;
 mId_AI27 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getMethods","()[Ljava/lang/reflect/Method;")
   ;
 mId_AI28 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getConstructors","()[Ljava/lang/reflect/Constructor;")
   ;
 mId_AI29 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getField","(Ljava/lang/String;)Ljava/lang/reflect/Field;")
   ;
 mId_AI30 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getMethod","(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;")
   ;
 mId_AI31 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getConstructor","([Ljava/lang/Class;)Ljava/lang/reflect/Constructor;")
   ;
 mId_AI32 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredClasses","()[Ljava/lang/Class;")
   ;
 mId_AI33 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredFields","()[Ljava/lang/reflect/Field;")
   ;
 mId_AI34 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredMethods","()[Ljava/lang/reflect/Method;")
   ;
 mId_AI35 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredConstructors","()[Ljava/lang/reflect/Constructor;")
   ;
 mId_AI36 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredField","(Ljava/lang/String;)Ljava/lang/reflect/Field;")
   ;
 mId_AI37 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredMethod","(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;")
   ;
 mId_AI38 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getDeclaredConstructor","([Ljava/lang/Class;)Ljava/lang/reflect/Constructor;")
   ;
 mId_AI39 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getResourceAsStream","(Ljava/lang/String;)Ljava/io/InputStream;")
   ;
 mId_AI40 =
    javabind_GetMethodID(javabind_class_java_lang_Class,"getResource","(Ljava/lang/String;)Ljava/net/URL;")
   ;}
