/* generated by javabind version 1.1a */
#include "JavaVM.oc.h"

jclass javabind_class_java_net_URL;

extern OBJ _Ajava_Anet_AURL_ASORT_AI1(OBJ x1){
 OBJ y;
 javabind_downcast(x1,javabind_class_java_net_URL,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Anet_AURL_ASORT_AI2(OBJ x1){
 OBJ y;
 javabind_downtest(x1,javabind_class_java_net_URL,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Anet_AURL_ASORT_AI3(OBJ x1){
 OBJ y;
 javabind_downcast(x1,javabind_class_java_net_URL,y);
 javabind_immutable_return(y);}

extern OBJ _Ajava_Anet_AURL_ASORT_AI4(OBJ x1){
 OBJ y;
 javabind_downtest(x1,javabind_class_java_net_URL,y);
 javabind_immutable_return(y);}


static void init_const_Ajava_Anet_AURL_ASORT(){
 javabind_class_java_net_URL = javabind_FindClass("java/net/URL");}
