#!/bin/sh
## script to set up control files and directory needed for a selftest
## $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/admin/selftest/initSelftest,v 1.1 1999-09-10 14:34:57 kd Exp $

## set up default values
ocstree=$HOME/ocs
selftestdir=`pwd`

# initialize variables
revision='$Revision: 1.1 $'
usage='--ocstree <PATH> --selftestdir <PATH>'

while [ $# -ge 1 ]
do
  case $1 in
    --ocstree)
      shift
      ocstree=$1
      shift
      ;;
    --selftestdir)
      shift
      selftestdir=$1
      shift
      ;;
    --version|--help|*)
      echo "initSelftest $revision"
      echo "$0 $usage"
      exit 0
   esac
done

ocsselftest=$ocstree/admin/selftest

#echo "ocstree = $ocstree"
#echo "selftestdir = $selftestdir"

if [ "$ocsselftest" != "$selftestdir" ] ; then
  echo "copying files from $ocsselftest ..."
  for f in ProjectDefs.selftest selftest Makefile; do
    echo " $ocsselftest/$f $selftestdir || exit 1"
    cp $ocsselftest/$f $selftestdir || exit 1
  done
fi

echo "setting up directory structure ..."

#directories which must be created, because we only use a subset of the
#original files in them
createDirs='src src/lib src/lib/Tools src/oc'
for d in $createDirs; do
  mkdir $selftestdir/$d || exit 2
  x=`echo $d | sed s:/:.:g`
  cp $ocsselftest/SysDefs.$x $selftestdir/$d/SysDefs || exit 2
done

# directories which are used in full and linked to the original ocs source tree
linkDirs='src/om src/lib/AggregateTypes src/lib/BasicTypes src/lib/Functions src/lib/Internal src/lib/System src/lib/Tools/Formatting src/oc/oc1 src/oc/oc2 src/oc/shared'
for l in $linkDirs; do
  ln -s $ocstree/$l $selftestdir/$l || exit 3
done

