#!/bin/bash

# Script template to rebuild Opal libraries
# 
# Usage to build and install a modified library living in teh ocs source tree:
# ocsadm ocs lib.<library name>
# ocsadm install lib.<library name>
# 
# The paths below have to be adapted (they must be identical to
# the paths in the Makefile).

VERSION=2.3n
OCSPROJECT=/afs/tu-berlin.de/units/Fak_IV/uebb/sw/sol11/ocs-2.3n/ProjectDefs
OCSHDIR=ocs-$VERSION
OCSHOME=/afs/tu-berlin.de/units/Fak_IV/uebb/sw/sol11/opt/$OCSHDIR
OCSSRC=/afs/tu-berlin.de/units/Fak_IV/uebb/sw/sol11/ocs-2.3n/src

OCSPROJECT=$OCSPROJECT $OCSHOME/bin/ocsadmin -ocshome $OCSHOME -ocssrc $OCSSRC -ocsspecs $OCSSRC/om/specs $@
