## $Header: /home/florenz/opal/home_uebb_CVS/CVS/ocs/src/proofchecker/oasyspc/pdriver/SysDefs.install,v 1.1 2000-01-27 21:03:44 kd Exp $

TOPSTRUCT  = TopLevel
TOPCOM	   = oasyspcbin
GENOPTIONS = -V -v1 
SUBNODES =  ../scripts
GENSUBSYS  = $(GENSTDSYS)


SOURCES=$(SIGNS) $(IMPLS) SysDefs ProjectDefs.in TopLevel.impl.readline TopLevel.impl.simple
COMPONENTS=$(SOURCES)
include $(OMLIBPATH)/GlobalRules.top
